# Generated by Django 4.0.1 on 2022-02-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customer_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('MALE', 'male'), ('FAMALE', 'famale')], max_length=10, null=True),
        ),
    ]
